Ratings
BadClup/internat-management pull request #3
Opened 2024-05-07 09:25 UTC by cooligus

2024-05-07 19:02 UTC, BaderBC requested changes
Resolve my comments, remove TODO after compleating them

The rest LGTM!

2024-05-07 19:02 UTC, BaderBC commented on server/db_docker/schema.sql
> +-- catering
this is a stop sign moment

2024-05-07 19:02 UTC, BaderBC commented on server/db_docker/schema.sql
> +-- rating
same as above

2024-05-07 19:02 UTC, BaderBC commented on server/db_docker/schema.sql
> +CREATE TABLE "rating"
it should be specified whether this table is for every user or only residents

2024-05-07 19:02 UTC, BaderBC commented on server/db_docker/schema.sql
> +CREATE TABLE "catering"
it's unclear what this table is responsible for

2024-05-07 19:02 UTC, BaderBC commented on server/db_docker/schema.sql
> +    stars      INT NOT NULL
stars only applies for for residents, what about supervisors which always gives `0-4` grades

2024-05-07 19:02 UTC, BaderBC commented on server/src/routes/rating/catering/get.rs
> +use super::super::rating::{CateringRatingDto, GetRatingReq, RatingsDto};
don't you think it would be better to reference with `crate::`?

2024-05-07 19:02 UTC, BaderBC commented on server/src/routes/rating/catering/get.rs
> +
I know it did the same in my previous code, but I saw that there is a way, to handle this more gently by using `match` statement

2024-05-07 19:02 UTC, BaderBC commented on server/src/routes/rating/catering/post.rs
> +use super::super::rating::{CateringRatingDto, RatingsDto};
I suggest using `crate::`

2024-05-07 19:02 UTC, BaderBC commented on server/src/routes/rating/catering/post.rs
> +    let mut result = vec![];
Same as above, try using `match`

2024-05-07 20:11 UTC, cooligus commented on server/db_docker/schema.sql
> +CREATE TABLE "catering"
could you suggest better name?
catering as date of "eating a dish"

2024-05-07 20:12 UTC, cooligus commented on server/db_docker/schema.sql
> +    stars      INT NOT NULL
i think it's still good (we can always create some checks)

2024-05-07 20:13 UTC, cooligus commented on server/src/routes/rating/catering/get.rs
> +use super::super::rating::{CateringRatingDto, GetRatingReq, RatingsDto};
it was spawning problems if I remember correctly

2024-05-07 20:13 UTC, cooligus commented on server/src/routes/rating/catering/get.rs
> +
I don't trust making new indents - if I can avoid them without physical injury, I do

2024-05-07 21:51 UTC, cooligus commented on server/db_docker/schema.sql
> +CREATE TABLE "rating"
IMO it should for both

2024-08-10 16:10 UTC, cooligus commented on server/db_docker/schema.sql
> +CREATE TABLE "rating"
division is clear (at this moment at least)

2024-08-10 16:11 UTC, cooligus commented on server/db_docker/schema.sql
> +CREATE TABLE "catering"
Never mind - I found one

2024-08-10 16:20 UTC, cooligus commented on server/src/routes/rating/catering/post.rs
> +    let mut result = vec![];
It causes annoying indents

2024-08-10 16:20 UTC, cooligus commented on server/src/routes/rating/catering/get.rs
> +use super::super::rating::{CateringRatingDto, GetRatingReq, RatingsDto};
But I'll try to do something with that

2024-09-09 21:05 UTC, BaderBC requested changes
Btw why did you requested a code review to pr which is still draft!?

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/catering/mod.rs
> +//pub mod delete;
?

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/mod.rs
> +        //.delete(catering::delete_catering_rating),
?

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/types.rs
> +    //pub created_at: DateTime<Utc>,
?

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/types.rs
> +}
What are these `Test*`  structs?

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/catering/get.rs
> +                //),
```suggestion
```

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/catering/get.rs
> +pub async fn get_catering_rating<'a>(
What do you think about splitting it into controller and logic. Controller would extract data and other stuff, while function with logic would make a db query

2024-09-09 21:05 UTC, BaderBC commented on server/src/routes/ratings/catering/post.rs
> +pub async fn post_catering_rating<'a>(
The same as above - consider splitting into logic and controller

2024-09-10 08:38 UTC, cooligus commented on server/src/routes/ratings/types.rs
> +}
Without ids

2024-10-04 09:34 UTC, BaderBC approved these changes

2024-10-04 14:59 UTC, merged